using System.Windows.Controls;
using System.Windows;
using System.Windows.Controls.Primitives;
using System.Windows.Input;

namespace MeasureControl.Views
{
    /// <summary>
    /// PXI4002A CAN 卡配置面板
    /// </summary>
    public partial class PXI4004CANConfigPanel : UserControl
    {
        public PXI4004CANConfigPanel()
        {
            // Try generated InitializeComponent if present; otherwise load XAML at runtime.
            // We call generated method by name via reflection to avoid compile-time dependency.
            var mi = this.GetType().GetMethod("InitializeComponent", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic);
            if (mi != null)
            {
                mi.Invoke(this, null);
            }
            else
            {
                // Fallback: load XAML resource manually
                try
                {
                    var asmName = "MeasureControl";
                    var uri = new System.Uri($"/{asmName};component/Views/TestTask/PXI4004CANConfigPanel.xaml", System.UriKind.Relative);
                    System.Windows.Application.LoadComponent(this, uri);
                }
                catch { }
            }
        }
 
        // NOTE: InitializeComponent is generated by XAML build step. Do NOT provide another overload here
 
        private void MenuOpenChannel_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var menuItem = sender as MenuItem;
                if (menuItem == null) return;
                var ctx = menuItem.Parent as ContextMenu ?? (menuItem.CommandTarget as ContextMenu);
                if (ctx == null) return;
                var rb = ctx.PlacementTarget as RadioButton;
                if (rb == null) return;
                var data = rb.DataContext;
                if (data == null) return;
                var idxProp = data.GetType().GetProperty("Index");
                if (idxProp == null) return;
                var idxObj = idxProp.GetValue(data);

                if (this.DataContext != null)
                {
                    var vm = this.DataContext;
                    var cmdProp = vm.GetType().GetProperty("OpenChannelCommand");
                    var cmd = cmdProp?.GetValue(vm) as ICommand;
                    if (cmd != null && cmd.CanExecute(idxObj))
                    {
                        cmd.Execute(idxObj);
                    }
                }
            }
            catch { }
        }

        private void MenuCloseChannel_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var menuItem = sender as MenuItem;
                if (menuItem == null) return;
                var ctx = menuItem.Parent as ContextMenu ?? (menuItem.CommandTarget as ContextMenu);
                if (ctx == null) return;
                var rb = ctx.PlacementTarget as RadioButton;
                if (rb == null) return;
                var data = rb.DataContext;
                if (data == null) return;
                var idxProp = data.GetType().GetProperty("Index");
                if (idxProp == null) return;
                var idxObj = idxProp.GetValue(data);

                if (this.DataContext != null)
                {
                    var vm = this.DataContext;
                    var cmdProp = vm.GetType().GetProperty("CloseChannelCommand");
                    var cmd = cmdProp?.GetValue(vm) as ICommand;
                    if (cmd != null && cmd.CanExecute(idxObj))
                    {
                        cmd.Execute(idxObj);
                    }
                }
            }
            catch { }
        }

        /// <summary>
        /// 数字输入验证：只允许输入正整数
        /// </summary>
        private void NumberValidationTextBox(object sender, TextCompositionEventArgs e)
        {
            // 只允许数字字符
            foreach (char c in e.Text)
            {
                if (!char.IsDigit(c))
                {
                    e.Handled = true;
                    break;
                }
            }
        }
    }
}